on: 
  
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "master","main" ]
    
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    # The flutter action needs java so include it
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Include the flutter action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    # Get flutter packages
    - run: flutter pub get
    #doctor
    - run: flutter doctor -v
    # Build :D
    - run: flutter build apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk